server.port: 8888

spring.cloud.config.server.git.uri: https://github.com/NatasaZvekic/DIS-config-server

spring.cloud.config.server.git: default-label=master
# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info

---
spring.config.activate.on-profile: docker
spring.cloud.config.server.git.uri: https://github.com/NatasaZvekic/DIS-config-server
