version: '2.1'

services:
  book:
    build: microservices/book
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_CONFIG_PROFILE=test
      - CONFIG_SERVER_USR=test
      - CONFIG_SERVER_PWD=test
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  rate:
    build: microservices/rate
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_CONFIG_PROFILE=test
      - CONFIG_SERVER_USR=test
      - CONFIG_SERVER_PWD=test
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  reader:
    build: microservices/reader
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_CONFIG_PROFILE=test
      - CONFIG_SERVER_USR=test
      - CONFIG_SERVER_PWD=test
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  comment:
    build: microservices/comment
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_CONFIG_PROFILE=test
      - CONFIG_SERVER_USR=test
      - CONFIG_SERVER_PWD=test
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  book-composite:
    build: microservices/book-composite
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_CONFIG_PROFILE=test
      - CONFIG_SERVER_USR=test
      - CONFIG_SERVER_PWD=test
    depends_on:
      rabbitmq:
        condition: service_healthy

  mongodb:
    image: mongo:3.6.9
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 5s
      timeout: 2s
      retries: 60

  rabbitmq:
    image: rabbitmq:3.8.11-management
    mem_limit: 512m
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 2s
      retries: 60

  eureka:
    build: spring-cloud/naming-server
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=test
      - CONFIG_SERVER_PWD=test

  gateway:
    build: spring-cloud/api-gateway
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=test
      - CONFIG_SERVER_PWD=test
    ports:
      - "8443:8443"
    depends_on:
      auth-server:
        condition: service_healthy

  auth-server:
    build: spring-cloud/authorization-server
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=test
      - CONFIG_SERVER_PWD=test
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:9999/actuator/health"]
      interval: 5s
      timeout: 2s
      retries: 60

  config-server:
    build: spring-cloud/config-server
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,git
      - SPRING_SECURITY_USER_NAME=test
      - SPRING_SECURITY_USER_PASSWORD=test

  zipkin:
    image: openzipkin/zipkin:2.23.2
    mem_limit: 1024m
    environment:
      - RABBIT_ADDRESSES=rabbitmq
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    depends_on:
      rabbitmq:
        condition: service_healthy