version: '2.1'

services:
  book:
    build: microservices/book
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  rate:
    build: microservices/rate
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  reader:
    build: microservices/reader
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  commend:
    build: microservices/comment
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  book-composite:
    build: microservices/book-composite
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
