spring.config.import: "configserver:"

spring:
    application.name: book
    cloud.config:
        failFast: true
        retry:
            initialInterval: 3000
            multiplier: 1.3
            maxInterval: 10000
            maxAttempts: 20
        uri: http://localhost:8888
        username: test
        password: test

---
#spring.config.activate.on-profile: docker

spring.cloud.config.uri: http://config-server:8888